config/routes.rb
Myplnr::Application.routes.draw do
  root :to => 'lists#index'

  resources :lists do
    resources :tasks do
      member do
        get :complete
      end

      collection do
        post :update_order
      end
    end
  end

end

app/models/list.rb
class List < ActiveRecord::Base
  include ActiveUUID::UUID
  self.primary_key = :id

  validates :uuid, :presence => true
  has_many :tasks

  # Get list title, return uuid if title is empty
  def title
    self[:title].blank? ? uuid : self[:title]
  end

  # Get tasks for provided quadrant
  def tasks_for_quadrant(id)
    tasks.where(quadrant: id)
  end
end

app/models/task.rb
class Task < ActiveRecord::Base
  validates :content, :presence => true
  validates :list_id, :presence => true
  validates_inclusion_of :completed, :in => [true, false]
  validates :quadrant, :presence => true

  default_scope :order => "sort ASC"

  belongs_to :list

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :username
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  include ActiveModel::ForbiddenAttributesProtection

  def list_params
    params.require(:list).permit(:id, :title)
  end

  def index
    @lists = List.all

    respond_to do |format|
      format.html
    end
  end

  def show
    @list = List.find(params[:id])
    @task = Task.new
    @task.quadrant = params[:quadrant] || 2

    respond_to do |format|
      format.html
    end
  end

  def new
    @list = List.new
    @list.uuid = SecureRandom.uuid
    @list.save

    respond_to do |format|
      format.html { redirect_to list_url(@list) }
    end
  end

  def update
    @list = List.find(params[:id])
    @list.update_attributes(list_params)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  include ActiveModel::ForbiddenAttributesProtection

  # Attributes Protection
  def task_params
    params.require(:task).permit(:id, :content, :completed, :quadrant, :list_id)
  end

  # Attributes protection for update task orders
  def task_order_params
    params.permit(:task_ids, :quadrant_id)
  end

  #
  # POST /tasks
  #

  def create
    @list = List.find(params[:list_id])
    @task = @list.tasks.build task_params
    if @task.save
      respond_to do |format|
        format.html { redirect_to list_url(@list, quadrant: @task.quadrant) }
        format.js
      end 
    else
      respond_to do |format|
        format.html { redirect_to list_url(@list), :notice => "Cannot save task!" }
        format.js
      end 
    end
  end

  # 
  # GET /tasks/1
  #

  def edit
    @list = List.find(params[:list_id])
    @task = Task.find(params[:id])

    respond_to do |format|
      format.js
    end
  end

  #
  # PUT /tasks/1
  #

  def update
    @task = Task.find(params[:id])

    if @task.update_attributes(task_params)
      respond_to do |format|
        format.js
      end
    else
      respond_to do |format|
        format.js
      end
    end
  end

  #
  # GET /tasks/1
  #

  def complete
    @task = Task.find(params[:id])

    if @task.update_attribute(:completed, @task.completed ? false : true)
      respond_to do |format|
        format.html { redirect_to list_url(@task.list) }
        format.js
      end 
    else
      respond_to do |format|
        format.html { redirect_to list_url(@task.list), :notice => "Cannot change complete status!" }
        format.js
      end 
    end
  end

  #
  # DELETE /tasks/1
  #

  def destroy
    @task = Task.find(params[:id])
    @task.destroy

    respond_to do |format|
      format.html { redirect_to list_url(@task.list) }
      format.js
    end
  end

  #
  # POST /tasks/1
  #

  def update_order
    quadrant = params[:quadrant]
    params[:task_ids].each_with_index do |task_id, index|
      task = Task.find(task_id)
      task.update_attributes(:quadrant => quadrant, :sort => index)
    end

    respond_to do |format|
      format.js
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/_navigation.html.erb
<nav class="top-bar" style="">
  <ul class="title-area">
    <li class="name">
      <h1><a href="/">MyPlnr</a></h1>
    </li>
  </ul>

  <section class="top-bar-section">
    <!-- Left Nav Section -->
    <ul class="left">
      <li class="divider"></li>
      <li>
        <%= link_to 'New List', new_list_path %>
      </li>
      <li class="divider"></li>
    </ul>
  </section>

  <section class="top-bar-section"> 
    <ul class="left">
      <li><%= yield(:top_bar) %> </li>
    </ul>
  </section>

  <section class="top-bar-section">
    <ul class="right">
      <li class="show_completed_toggle">
        <input type="checkbox" id="show_completed" name="show_completed">
        <label>Show completed tasks</label>
      </li>
    </ul>
  </section>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

  	<%= stylesheet_link_tag    "application" %>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render "layouts/navigation" %>
    <%= yield %>
    <div id="global_loader"></div>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/lists/_form.html.erb
<div class="listFormWrapper">
  <%= form_for @list, :remote => true do |f| %>
    <div class="inputWrapper">
      <%= f.text_field :title, :autocomplete => "off", :placeholder => "List Title" %>
    </div>

    <div class="inputWrapper submit">
      <%= f.submit %>
      <a href="#" class="cancel">Cancel</a>
    </div>
  <% end %>
</div>

app/views/lists/_quadrant.html.erb
<%= content_tag "ul", :id => id, :class => "tasks panel quadrantWrapper large-6 columns q#{id}" do %>
  <% @list.tasks_for_quadrant(id).each do |task| %>
    <%= render task %>
  <% end %>

  <%= render 'tasks/form' if @task.quadrant == id %>

  <li class="large-12 addTask columns <%= 'hidden' if @task.quadrant == id %>">
    <div class="row">
      <div class="large-1 columns"> </div>
      <%= link_to "Add New Task", list_path(@list, :quadrant => id), :data => {:add_task => id}, :class => 'large-11 columns' %>
    </div>
  </li>
<% end %>

app/views/lists/index.html.erb
<div class="row">
  <div class='large-six columns'>
    <ul class="panel listsWrapper">
      <% @lists.each do |list| %>
        <li><%= link_to list.title, list %></li>
      <% end %>
    </ul>
  </div>
</div>

app/views/lists/show.html.erb
<%= content_for :top_bar do %>
  <h1 class="listTitle">
    <a href="#"><%= @list.title %></a>
  </h1>
  <%= render "lists/form" %>
<% end %>

<div class="quadrantsWrapper large-12 small-12 columns" data-uuid=<%= @list.id %>>
  <div class="row">
    <%= render 'quadrant', :id => 2 %>
    <%= render 'quadrant', :id => 1 %>
  </div>
  <div class="row">
    <%= render 'quadrant', :id => 3 %>
    <%= render 'quadrant', :id => 4 %>
  </div>
</div>

app/views/tasks/_form.html.erb
<li class="taskForm large-12 small-12 columns">
<%= form_for [@list, @task], :remote => true do |t| %>
  <%= t.hidden_field :quadrant %>

  <div class="row">
    <div class="large-1 small-1 columns">
      <%= t.check_box :completed %>
    </div>

    <div class="large-11 small-11 columns">
      <%= t.text_field :content, :placeholder => 'Task', :tabindex => 1, :autocomplete => "off" %>
    </div>
  </div>

  <div class="row">
    <div class="large-1 small-1 columns"> </div>

    <div class="large-11 small-11 columns submit">
      <%= t.submit "Save Task" %>
      <a href="#" class="cancel">Cancel</a>
    </div>
  </div>
<% end %>
</li>

app/views/tasks/_task.html.erb
<li id=task-<%= task.id %> data-task-id=<%= task.id %> class="task large-12 small-12 columns <%= 'completed' if task.completed %>">
<div class="row">
  <span class="large-1 small-1 columns">
    <%= check_box :task, 
      :complete,
      :checked => task.completed ? true : false, 
      :data => {:toggle => :complete, :url => complete_list_task_path(task.list, task)}
    %>
  </span>

  <span class='large-10 small-10 columns'><%= task.content %></span>

  <div class='large-1 small-1 columns actionsWrapper'>
    <%= link_to list_task_path(task.list, task), :method => :delete, :remote => true, :class => 'deleteTask' do %>
      <i class="general foundicon-trash"></i>
    <% end %>
  </div>
</div>
</li>